name: 'gg-sql-migration'
description: 'SQL migration'
inputs:
  connection_string:
    description: 'Connection string to the database'
    required: true
  config_path:
    description: 'Path to the configuration file'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ggrouppfoundation/gg-sql-migration:latest'
  env:
    CONNECTION_STRING: ${{ inputs.connection_string }}
    CONFIG_PATH: ${{ inputs.config_path }}
  args:
    - '--build-arg'
    - 'GG_NUGET_SOURCE_URL=${{ secrets.GG_NUGET_SOURCE_URL }}'
    - 'GG_NUGET_SOURCE_USER=${{ secrets.GG_NUGET_SOURCE_USER_NAME }}'
    - 'GG_NUGET_SOURCE_PASSWORD=${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}'