name: 'gg-sql-migration'
description: 'SQL migration'
inputs:
  connection_string:
    description: 'Connection string to the database'
    required: true
  config_path:
    description: 'Path to the configuration file'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ggrouppfoundation/gg-sql-migration:latest'
  args:
    - ${{ inputs.connection_string }}
    - ${{ inputs.config_path }}